repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-yaml
      - id: check-json
        exclude: "(?x)^(\n  apps/web/tsconfig.*\\.json$\n  |townley-platform/frontend/tsconfig.*\\.json$\n)$"

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.12
        files: ^townley-platform/backend/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: [--fix]
        files: ^townley-platform/backend/
      - id: ruff-format
        files: ^townley-platform/backend/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        files: ^townley-platform/backend/
        args:
          - --ignore-missing-imports
        additional_dependencies:
          - sqlalchemy2-stubs
          - types-redis
