/*
  Auto-generated Full Legacy Parity Checks
  Source legacy schema file: Townleyfulldatabaseschema.sql
  Generated: 2025-12-28 04:14:20

  Purpose:
  - Assert that the CURRENT database contains all legacy tables/columns (dbo.* etc.)
  - Detect mismatches in data type, length, precision/scale, nullability, identity

  Usage:
    sqlcmd -S localhost -U sa -P "..." -d Townley_MySQL -i /scripts/parity_legacy_full.sql

  Notes:
  - For nvarchar/nchar, sys.columns.max_length is BYTES (so nvarchar(100) => 200).
  - For varchar/char, max_length is characters.
  - This script reports mismatches; it does not modify schema.
*/
SET NOCOUNT ON;
PRINT '=== Full Legacy Parity Checks ===';
PRINT 'DB: ' + DB_NAME();

IF OBJECT_ID('tempdb..#ExpectedColumns') IS NOT NULL DROP TABLE #ExpectedColumns;
CREATE TABLE #ExpectedColumns (
  schema_name sysname NOT NULL,
  table_name  sysname NOT NULL,
  column_name sysname NOT NULL,
  data_type   sysname NOT NULL,
  max_length  int NULL,
  precision_val tinyint NULL,
  scale_val tinyint NULL,
  is_nullable bit NOT NULL,
  is_identity bit NOT NULL
);
INSERT INTO #ExpectedColumns VALUES
  ('dbo','AlloySpecifications','Id','int',NULL,NULL,NULL,0,1),
  ('dbo','AlloySpecifications','AlloyCode','nvarchar',200,NULL,NULL,0,0),
  ('dbo','AlloySpecifications','Description','nvarchar',510,NULL,NULL,1,0),
  ('dbo','AlloySpecifications','TargetCarbon','float',NULL,NULL,NULL,1,0),
  ('dbo','AlloySpecifications','TargetSilicon','float',NULL,NULL,NULL,1,0),
  ('dbo','AlloySpecifications','TargetManganese','float',NULL,NULL,NULL,1,0),
  ('dbo','AlloySpecifications','Created_At','datetime',NULL,NULL,NULL,1,0),
  ('dbo','Aproveusers','Code','nvarchar',100,NULL,NULL,1,0),
  ('dbo','Aproveusers','Name','nvarchar',100,NULL,NULL,1,0),
  ('dbo','Aproveusers','Email','nvarchar',100,NULL,NULL,1,0),
  ('dbo','Aproveusers','Select','bit',NULL,NULL,NULL,1,0),
  ('dbo','AssemblyRecords','Id','int',NULL,NULL,NULL,0,1),
  ('dbo','AssemblyRecords','WorkOrderId','int',NULL,NULL,NULL,0,0),
  ('dbo','AssemblyRecords','AssemblyDate','date',NULL,NULL,NULL,1,0),
  ('dbo','AssemblyRecords','Assembler','nvarchar',200,NULL,NULL,1,0),
  ('dbo','AssemblyRecords','AssemblyNotes','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','AssemblyRecords','CreatedAt','datetime',NULL,NULL,NULL,1,0),
  ('dbo','AssemblyRecords','UpdatedAt','datetime',NULL,NULL,NULL,1,0),
  ('dbo','Attachedfiles','MainScrapTblID','int',NULL,NULL,NULL,1,0),
  ('dbo','Attachedfiles','FileType','nchar',20,NULL,NULL,1,0),
  ('dbo','Attachedfiles','FileName','nvarchar',100,NULL,NULL,1,0),
  ('dbo','Attachedfiles','FilePath','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','Attachedfiles','AddDateTime','datetime',NULL,NULL,NULL,1,0),
  ('dbo','Attachedfiles','Username','nvarchar',100,NULL,NULL,1,0),
  ('dbo','Attachedfiles','Deleted','int',NULL,NULL,NULL,1,0),
  ('dbo','Attachedfiles','GridNumber','int',NULL,NULL,NULL,1,0),
  ('dbo','Attachedfiles','ID','int',NULL,NULL,NULL,0,1),
  ('dbo','AuditLogs','Id','int',NULL,NULL,NULL,0,1),
  ('dbo','AuditLogs','UserId','int',NULL,NULL,NULL,0,0),
  ('dbo','AuditLogs','Action','nvarchar',200,NULL,NULL,0,0),
  ('dbo','AuditLogs','Resource','nvarchar',400,NULL,NULL,1,0),
  ('dbo','AuditLogs','Details','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','AuditLogs','Timestamp','datetime',NULL,NULL,NULL,1,0),
  ('dbo','AuditLogs','RecordedBy','nvarchar',200,NULL,NULL,1,0),
  ('dbo','CastingType','ID','int',NULL,NULL,NULL,0,1),
  ('dbo','CastingType','CastingType','nvarchar',100,NULL,NULL,0,0),
  ('dbo','CastingType','SubCat','int',NULL,NULL,NULL,1,0),
  ('dbo','ChemAddRecords','Id','int',NULL,NULL,NULL,0,1),
  ('dbo','ChemAddRecords','WorkOrderId','int',NULL,NULL,NULL,0,0),
  ('dbo','ChemAddRecords','AddDate','date',NULL,NULL,NULL,1,0),
  ('dbo','ChemAddRecords','Element','nvarchar',200,NULL,NULL,1,0),
  ('dbo','ChemAddRecords','QuantityAdded','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemAddRecords','Operator','nvarchar',200,NULL,NULL,1,0),
  ('dbo','ChemAddRecords','Reason','nvarchar',400,NULL,NULL,1,0),
  ('dbo','ChemAddRecords','CreatedAt','datetime',NULL,NULL,NULL,1,0),
  ('dbo','ChemAddRecords','UpdatedAt','datetime',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryRecords','Id','int',NULL,NULL,NULL,0,1),
  ('dbo','ChemistryRecords','WorkOrderId','int',NULL,NULL,NULL,0,0),
  ('dbo','ChemistryRecords','ChemTestDate','date',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryRecords','SampleId','nvarchar',200,NULL,NULL,1,0),
  ('dbo','ChemistryRecords','ChemOperator','nvarchar',200,NULL,NULL,1,0),
  ('dbo','ChemistryRecords','ResultJSON','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','ChemistryRecords','CreatedAt','datetime',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryRecords','UpdatedAt','datetime',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','id','int',NULL,NULL,NULL,0,1),
  ('dbo','ChemistryResults','work_order_id','bigint',NULL,NULL,NULL,0,0),
  ('dbo','ChemistryResults','heat_number','nvarchar',100,NULL,NULL,1,0),
  ('dbo','ChemistryResults','sample_number','nvarchar',100,NULL,NULL,1,0),
  ('dbo','ChemistryResults','date_poured','datetime',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','furnace','nvarchar',100,NULL,NULL,1,0),
  ('dbo','ChemistryResults','alloy_code','nvarchar',100,NULL,NULL,1,0),
  ('dbo','ChemistryResults','gross_weight','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','tap_temp','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','C','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','Si','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','Mn','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','P','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','S','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','Ni','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','Cr','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','Mo','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','V','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','Cu','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','Fe','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','W','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','Ti','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','Sn','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','Co','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','Al','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','Cb','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','Pb','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','B','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','Nb','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','Zr','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','Mg','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','Ce','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','Ta','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','N','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','Ceq','float',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','notes','nvarchar',510,NULL,NULL,1,0),
  ('dbo','ChemistryResults','created_at','datetime',NULL,NULL,NULL,0,0),
  ('dbo','ChemistryResults','updated_at','datetime',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults','UpdatedAt','datetime',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults_Audit','AuditID','int',NULL,NULL,NULL,0,1),
  ('dbo','ChemistryResults_Audit','ActionType','nvarchar',20,NULL,NULL,1,0),
  ('dbo','ChemistryResults_Audit','ChangedAt','datetime',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults_Audit','ChangedBy','nvarchar',200,NULL,NULL,1,0),
  ('dbo','ChemistryResults_Audit','Original_id','int',NULL,NULL,NULL,1,0),
  ('dbo','ChemistryResults_Audit','DataBefore','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','ChemistryResults_Audit','DataAfter','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','Customers','CustomerNumber','varchar',50,NULL,NULL,0,0),
  ('dbo','Customers','CustomerName','varchar',100,NULL,NULL,1,0),
  ('dbo','Defect_sub_Category','ID','int',NULL,NULL,NULL,0,1),
  ('dbo','Defect_sub_Category','Code','nvarchar',100,NULL,NULL,0,0),
  ('dbo','Defect_sub_Category','Description','nvarchar',510,NULL,NULL,0,0),
  ('dbo','Defect_sub_Category','DefectCategory','nvarchar',20,NULL,NULL,0,0),
  ('dbo','Defect_sub_Category','Select','bit',NULL,NULL,NULL,1,0),
  ('dbo','DefectCategory','ID','int',NULL,NULL,NULL,0,1),
  ('dbo','DefectCategory','Code','nvarchar',100,NULL,NULL,0,0),
  ('dbo','DefectCategory','Description','nvarchar',510,NULL,NULL,0,0),
  ('dbo','DefectCategory','Select','bit',NULL,NULL,NULL,0,0),
  ('dbo','DefectCommonName','ID','int',NULL,NULL,NULL,0,1),
  ('dbo','DefectCommonName','Code','nvarchar',100,NULL,NULL,0,0),
  ('dbo','DefectCommonName','Description','nvarchar',510,NULL,NULL,0,0),
  ('dbo','DefectCommonName','Defect_sub2_Category','nvarchar',20,NULL,NULL,0,0),
  ('dbo','DefectCommonName','CommonName','nvarchar',510,NULL,NULL,0,0),
  ('dbo','DefectCommonName','select','bit',NULL,NULL,NULL,0,0),
  ('dbo','Departments','ID','int',NULL,NULL,NULL,0,1),
  ('dbo','Departments','Description','nvarchar',100,NULL,NULL,0,0),
  ('dbo','Documents','Id','int',NULL,NULL,NULL,0,1),
  ('dbo','Documents','WorkOrderId','int',NULL,NULL,NULL,0,0),
  ('dbo','Documents','FileName','nvarchar',510,NULL,NULL,1,0),
  ('dbo','Documents','FileType','nvarchar',100,NULL,NULL,1,0),
  ('dbo','Documents','UploadedBy','nvarchar',510,NULL,NULL,1,0),
  ('dbo','Documents','UploadedAt','datetime',NULL,NULL,NULL,1,0),
  ('dbo','Employees','ID','int',NULL,NULL,NULL,0,1),
  ('dbo','Employees','Name','nvarchar',100,NULL,NULL,0,0),
  ('dbo','Employees','DeptID','int',NULL,NULL,NULL,0,0),
  ('dbo','Employees','EmailAddress','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','FinishingRecords','Id','int',NULL,NULL,NULL,0,1),
  ('dbo','FinishingRecords','WorkOrderId','int',NULL,NULL,NULL,1,0),
  ('dbo','FinishingRecords','FinishDate','datetime',NULL,NULL,NULL,1,0),
  ('dbo','FinishingRecords','Process','nvarchar',100,NULL,NULL,1,0),
  ('dbo','FinishingRecords','Notes','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','FinishingRecords','UpdatedAt','datetime',NULL,NULL,NULL,1,0),
  ('dbo','FinishingRecords_Audit','AuditID','int',NULL,NULL,NULL,0,1),
  ('dbo','FinishingRecords_Audit','ActionType','nvarchar',20,NULL,NULL,1,0),
  ('dbo','FinishingRecords_Audit','ChangedAt','datetime',NULL,NULL,NULL,1,0),
  ('dbo','FinishingRecords_Audit','ChangedBy','nvarchar',200,NULL,NULL,1,0),
  ('dbo','FinishingRecords_Audit','Original_Id','int',NULL,NULL,NULL,1,0),
  ('dbo','FinishingRecords_Audit','DataBefore','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','FinishingRecords_Audit','DataAfter','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','FinishTime','RecordID','float',NULL,NULL,NULL,1,0),
  ('dbo','FinishTime','Finish Date','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FinishTime','Finish Hours','float',NULL,NULL,NULL,1,0),
  ('dbo','FinishTime','Finished By','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FinishTime','Hardness','float',NULL,NULL,NULL,1,0),
  ('dbo','FinishTime','Qty To Work On','float',NULL,NULL,NULL,1,0),
  ('dbo','FinishTime','Qty to credit','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FinishTime','No# Finished','float',NULL,NULL,NULL,1,0),
  ('dbo','FinishTime','Finish Notes','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FinishTime','ID','float',NULL,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','RecordNo','float',NULL,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','WorkOrderNo','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','ShiftAssign','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','MoldAssignDate','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','PurchaseOrderNo','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','WorkOrderAssign','bit',NULL,NULL,NULL,0,0),
  ('dbo','FoundryWorkData','Rider','bit',NULL,NULL,NULL,0,0),
  ('dbo','FoundryWorkData','MachineAssignDate','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','MachineRider','bit',NULL,NULL,NULL,0,0),
  ('dbo','FoundryWorkData','Customer','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','PartNo','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','SerialNo','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','PartDescription','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','StockpiledPart','bit',NULL,NULL,NULL,0,0),
  ('dbo','FoundryWorkData','Alloy','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','AlloyAutoNumber','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','ItemWeight','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','QtyRequired','float',NULL,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','QtyToManufacture','float',NULL,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','WHSLocation','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','GrindingToShip','bit',NULL,NULL,NULL,0,0),
  ('dbo','FoundryWorkData','HeatTreatRequired','bit',NULL,NULL,NULL,0,0),
  ('dbo','FoundryWorkData','JobComplete','bit',NULL,NULL,NULL,0,0),
  ('dbo','FoundryWorkData','FinalInspecPerformedBy','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','SpecialMfgInstructions','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','Notes','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','MoldingFinished','bit',NULL,NULL,NULL,0,0),
  ('dbo','FoundryWorkData','PouringFinished','bit',NULL,NULL,NULL,0,0),
  ('dbo','FoundryWorkData','ShakeoutFinished','bit',NULL,NULL,NULL,0,0),
  ('dbo','FoundryWorkData','FinishingFinished','bit',NULL,NULL,NULL,0,0),
  ('dbo','FoundryWorkData','HeatTreatFinished','bit',NULL,NULL,NULL,0,0),
  ('dbo','FoundryWorkData','MachiningFinished','bit',NULL,NULL,NULL,0,0),
  ('dbo','FoundryWorkData','AssemblyFinished','bit',NULL,NULL,NULL,0,0),
  ('dbo','FoundryWorkData','Scrapped','bit',NULL,NULL,NULL,0,0),
  ('dbo','FoundryWorkData','DateScrapped','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','NoScrapped','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','ReasonScrapped','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','ResponsibleScrapLocation','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','RootCauseForScrap','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','CNCProgram','bit',NULL,NULL,NULL,0,0),
  ('dbo','FoundryWorkData','ReasonLate','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','SpecialInstructions','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','ComputerName','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','Rush','bit',NULL,NULL,NULL,0,0),
  ('dbo','FoundryWorkData','RushDueDate','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','Type','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','PourWt','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','Remake','bit',NULL,NULL,NULL,0,0),
  ('dbo','FoundryWorkData','HeatSchedulesid','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','Machinenumber','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','ScheduleFlag','bit',NULL,NULL,NULL,0,0),
  ('dbo','FoundryWorkData','RecStatus','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','INVLocation','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','RecordType','float',NULL,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','PartAdded','bit',NULL,NULL,NULL,0,0),
  ('dbo','FoundryWorkData','DueDate','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','MachShopDate','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','ReleasedToShippingDate','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','FinalInspecDate','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','DateEntered','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','MoldingDueDate','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','PouringSch','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','ShakeOutSch','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','ShakeOutComp','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','GrindingSch','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','HeatTreatSch','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','SurfaceGrdSch','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','SurfaceGrdComp','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','BoringSch','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','BoringComp','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','DrillingSch','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','DrillingComp','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','STBalancingSch','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','STBalancingComp','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','DynBalancingSch','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','DynBalancingComp','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','FinalInspComp','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','PaintToShip','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','MillingComp','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','HeatTreatComp','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','DeliveryComp','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','MoldSetupComp','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','MoldingComp','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','PatternComp','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','ThreadingComp','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','PouringComp','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','GrindingComp','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','RiderPrinted','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','PartTranscode','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','ProdctionFinshed','bit',NULL,NULL,NULL,0,0),
  ('dbo','FoundryWorkData','MachineNotes','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','Statusnotes','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','CustomerNumber','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','MachineComp','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','MfgCncComp','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','Cryocomp','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','InvDateTime','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','PouringScheduleFlag','bit',NULL,NULL,NULL,0,0),
  ('dbo','FoundryWorkData','PourAssignDate','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','PRRecStatus','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','ShippingDate','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','ReleasedToShippingFlag','nvarchar',510,NULL,NULL,1,0),
  ('dbo','FoundryWorkData','Specialflag','bit',NULL,NULL,NULL,0,0),
  ('dbo','HeatTreatRecords','WorkOrderId','int',NULL,NULL,NULL,0,0),
  ('dbo','HeatTreatRecords','TreatDate','date',NULL,NULL,NULL,1,0),
  ('dbo','HeatTreatRecords','Temperature','float',NULL,NULL,NULL,1,0),
  ('dbo','HeatTreatRecords','DurationHours','float',NULL,NULL,NULL,1,0),
  ('dbo','HeatTreatRecords','Notes','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','HeatTreatTime','RecordTie','float',NULL,NULL,NULL,1,0),
  ('dbo','HeatTreatTime','HeatTreatDate','nvarchar',510,NULL,NULL,1,0),
  ('dbo','HeatTreatTime','QtyHeated','float',NULL,NULL,NULL,1,0),
  ('dbo','HeatTreatTime','NoHeatTreat','float',NULL,NULL,NULL,1,0),
  ('dbo','HeatTreatTime','HeatNos','float',NULL,NULL,NULL,1,0),
  ('dbo','HeatTreatTime','HeatTreatFurnaceNo','float',NULL,NULL,NULL,1,0),
  ('dbo','HeatTreatTime','HeatTreatHardness','float',NULL,NULL,NULL,1,0),
  ('dbo','HeatTreatTime','HeatTreatNotes','nvarchar',510,NULL,NULL,1,0),
  ('dbo','HeatTreatTime','HeatTreatProcessNo','nvarchar',510,NULL,NULL,1,0),
  ('dbo','HeatTreatTime','ID','float',NULL,NULL,NULL,1,0),
  ('dbo','InspectionRecords','Id','int',NULL,NULL,NULL,0,1),
  ('dbo','InspectionRecords','WorkOrderId','int',NULL,NULL,NULL,0,0),
  ('dbo','InspectionRecords','InspectionDate','date',NULL,NULL,NULL,1,0),
  ('dbo','InspectionRecords','Inspector','nvarchar',200,NULL,NULL,1,0),
  ('dbo','InspectionRecords','InspectionNotes','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','InspectionRecords','Pass','bit',NULL,NULL,NULL,1,0),
  ('dbo','InspectionRecords','CreatedAt','datetime',NULL,NULL,NULL,1,0),
  ('dbo','InspectionRecords','UpdatedAt','datetime',NULL,NULL,NULL,1,0),
  ('dbo','LSTCub_2_Categories','ID','int',NULL,NULL,NULL,0,1),
  ('dbo','LSTCub_2_Categories','Code','nvarchar',100,NULL,NULL,0,0),
  ('dbo','LSTCub_2_Categories','Description','nvarchar',510,NULL,NULL,0,0),
  ('dbo','LSTCub_2_Categories','Defect_sub_Category','nvarchar',20,NULL,NULL,0,0),
  ('dbo','LSTCub_2_Categories','Select','bit',NULL,NULL,NULL,0,0),
  ('dbo','MachineTime','Record','float',NULL,NULL,NULL,1,0),
  ('dbo','MachineTime','NoMachined','float',NULL,NULL,NULL,1,0),
  ('dbo','MachineTime','MachineHrs','nvarchar',510,NULL,NULL,1,0),
  ('dbo','MachineTime','MachineNotes','nvarchar',510,NULL,NULL,1,0),
  ('dbo','MachineTime','QtyReleasedToShipping','float',NULL,NULL,NULL,1,0),
  ('dbo','MachineTime','CNCMachined','bit',NULL,NULL,NULL,0,0),
  ('dbo','MachineTime','StartWht','float',NULL,NULL,NULL,1,0),
  ('dbo','MachineTime','EndWht','float',NULL,NULL,NULL,1,0),
  ('dbo','MachineTime','ID','float',NULL,NULL,NULL,1,0),
  ('dbo','MachineTime','MachineDate','datetime',NULL,NULL,NULL,1,0),
  ('dbo','MachineTime','UpdatedAt','datetime',NULL,NULL,NULL,1,0),
  ('dbo','MachineTime_Audit','AuditID','int',NULL,NULL,NULL,0,1),
  ('dbo','MachineTime_Audit','ActionType','nvarchar',20,NULL,NULL,1,0),
  ('dbo','MachineTime_Audit','ChangedAt','datetime',NULL,NULL,NULL,1,0),
  ('dbo','MachineTime_Audit','ChangedBy','nvarchar',200,NULL,NULL,1,0),
  ('dbo','MachineTime_Audit','Original_ID','int',NULL,NULL,NULL,1,0),
  ('dbo','MachineTime_Audit','DataBefore','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','MachineTime_Audit','DataAfter','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','ID','int',NULL,NULL,NULL,0,1),
  ('dbo','MainScrapTbl','RecordNumber','int',NULL,NULL,NULL,0,0),
  ('dbo','MainScrapTbl','SearialNum','nvarchar',100,NULL,NULL,0,0),
  ('dbo','MainScrapTbl','WorkorderNo','nvarchar',100,NULL,NULL,0,0),
  ('dbo','MainScrapTbl','PartNo','nvarchar',100,NULL,NULL,0,0),
  ('dbo','MainScrapTbl','Alloy','nvarchar',100,NULL,NULL,0,0),
  ('dbo','MainScrapTbl','Description','nvarchar',-1,NULL,NULL,0,0),
  ('dbo','MainScrapTbl','MfgInst','nvarchar',-1,NULL,NULL,0,0),
  ('dbo','MainScrapTbl','DefectCategory','nvarchar',100,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','Defect_sub_Category','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','LSTCub_2_Categories','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','DefectCommonName','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','Employee','nvarchar',100,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','Department','nvarchar',100,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','EntryDate','date',NULL,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','Defect','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','AnalysisBy','nvarchar',100,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','AnalysisDate','nvarchar',100,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','Scrapping','bit',NULL,NULL,NULL,0,0),
  ('dbo','MainScrapTbl','ProblemStatment','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','DataColected','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','DataEvaluation','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','CorrectivePlan','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','Actiontrial','bit',NULL,NULL,NULL,0,0),
  ('dbo','MainScrapTbl','DecribeActionTrial','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','EvaluationActionTrial','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','EvaluationProductionTest','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','ResultApprovedby','nvarchar',100,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','ResultApprovedbyDate','date',NULL,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','ProductionTestApp','nvarchar',100,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','ProductionTestdate','date',NULL,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','sourcedefectcorrected','bit',NULL,NULL,NULL,0,0),
  ('dbo','MainScrapTbl','ItemWeight','int',NULL,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','PatternLabel','nvarchar',100,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','PlanAppby','nvarchar',100,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','PlanAppDate','date',NULL,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','solutiondoc','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','QAMgr','nvarchar',100,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','QAMgrDate','date',NULL,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','DefectCommonNameTXT','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','lstPlanAppby','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','lstAnalysisBy','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','ProposedCorr','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','NewPartSerial','nvarchar',100,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','FollowupProd','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','ActionImpProd','bit',NULL,NULL,NULL,1,0),
  ('dbo','MainScrapTbl','UpdatedAt','datetime',NULL,NULL,NULL,1,0),
  ('dbo','MainScrapTbl_Audit','AuditID','int',NULL,NULL,NULL,0,1),
  ('dbo','MainScrapTbl_Audit','ActionType','nvarchar',20,NULL,NULL,1,0),
  ('dbo','MainScrapTbl_Audit','ChangedAt','datetime',NULL,NULL,NULL,1,0),
  ('dbo','MainScrapTbl_Audit','ChangedBy','nvarchar',200,NULL,NULL,1,0),
  ('dbo','MainScrapTbl_Audit','Original_ID','int',NULL,NULL,NULL,1,0),
  ('dbo','MainScrapTbl_Audit','DataBefore','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','MainScrapTbl_Audit','DataAfter','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','MoldingRecords','RecordNo','int',NULL,NULL,NULL,0,1),
  ('dbo','MoldingRecords','WorkOrderNo','nvarchar',100,NULL,NULL,0,0),
  ('dbo','MoldingRecords','MoldDate','date',NULL,NULL,NULL,0,0),
  ('dbo','MoldingRecords','MoldShift','nvarchar',40,NULL,NULL,1,0),
  ('dbo','MoldingRecords','MoldOperator','nvarchar',200,NULL,NULL,1,0),
  ('dbo','MoldingRecords','PatternNo','nvarchar',100,NULL,NULL,1,0),
  ('dbo','MoldingRecords','Alloy','nvarchar',100,NULL,NULL,1,0),
  ('dbo','MoldingRecords','PartNo','nvarchar',100,NULL,NULL,1,0),
  ('dbo','MoldingRecords','MoldNotes','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','MoldingRecords','MoldingFinished','bit',NULL,NULL,NULL,1,0),
  ('dbo','MoldingRecords','CreatedAt','datetime',NULL,NULL,NULL,1,0),
  ('dbo','MoldingRecords','UpdatedAt','datetime',NULL,NULL,NULL,1,0),
  ('dbo','MoldTime','Record No','float',NULL,NULL,NULL,1,0),
  ('dbo','MoldTime','Date Molded','nvarchar',510,NULL,NULL,1,0),
  ('dbo','MoldTime','Shift Molded','nvarchar',510,NULL,NULL,1,0),
  ('dbo','MoldTime','No Molded','float',NULL,NULL,NULL,1,0),
  ('dbo','MoldTime','MoldManHrs','float',NULL,NULL,NULL,1,0),
  ('dbo','MoldTime','Mold Notes','nvarchar',510,NULL,NULL,1,0),
  ('dbo','MoldTime','1000Resin #/min','float',NULL,NULL,NULL,1,0),
  ('dbo','MoldTime','1000Catalyst #/min','float',NULL,NULL,NULL,1,0),
  ('dbo','MoldTime','1000Sand #/min','float',NULL,NULL,NULL,1,0),
  ('dbo','MoldTime','1000LOI %','float',NULL,NULL,NULL,1,0),
  ('dbo','MoldTime','600Resin #/min','float',NULL,NULL,NULL,1,0),
  ('dbo','MoldTime','600Catalyst #/min','float',NULL,NULL,NULL,1,0),
  ('dbo','MoldTime','600Sand #/min','float',NULL,NULL,NULL,1,0),
  ('dbo','MoldTime','600LOI %','float',NULL,NULL,NULL,1,0),
  ('dbo','MoldTime','ID','float',NULL,NULL,NULL,1,0),
  ('dbo','Parts','PartNo','varchar',50,NULL,NULL,0,0),
  ('dbo','Parts','PartDescription','varchar',255,NULL,NULL,1,0),
  ('dbo','Parts','Alloy','varchar',50,NULL,NULL,1,0),
  ('dbo','PouringRecords','Id','int',NULL,NULL,NULL,0,1),
  ('dbo','PouringRecords','WorkOrderId','int',NULL,NULL,NULL,1,0),
  ('dbo','PouringRecords','PourDate','datetime',NULL,NULL,NULL,1,0),
  ('dbo','PouringRecords','Alloy','nvarchar',100,NULL,NULL,1,0),
  ('dbo','PouringRecords','Notes','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','PouringRecords','UpdatedAt','datetime',NULL,NULL,NULL,1,0),
  ('dbo','PouringRecords','HeatNo','varchar',50,NULL,NULL,1,0),
  ('dbo','PouringRecords','TapTemp','decimal',NULL,5,2,1,0),
  ('dbo','PouringRecords','PourTemp','decimal',NULL,5,2,1,0),
  ('dbo','PouringRecords','Furnace','varchar',50,NULL,NULL,1,0),
  ('dbo','PouringRecords','Ladle','varchar',50,NULL,NULL,1,0),
  ('dbo','PouringRecords','Pourer','varchar',100,NULL,NULL,1,0),
  ('dbo','PouringRecords_Audit','AuditID','int',NULL,NULL,NULL,0,1),
  ('dbo','PouringRecords_Audit','ActionType','nvarchar',20,NULL,NULL,1,0),
  ('dbo','PouringRecords_Audit','ChangedAt','datetime',NULL,NULL,NULL,1,0),
  ('dbo','PouringRecords_Audit','ChangedBy','nvarchar',200,NULL,NULL,1,0),
  ('dbo','PouringRecords_Audit','Original_Id','int',NULL,NULL,NULL,1,0),
  ('dbo','PouringRecords_Audit','DataBefore','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','PouringRecords_Audit','DataAfter','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','PouringTime','RecordLink','float',NULL,NULL,NULL,1,0),
  ('dbo','PouringTime','DatePoured','nvarchar',510,NULL,NULL,1,0),
  ('dbo','PouringTime','NoPoured','float',NULL,NULL,NULL,1,0),
  ('dbo','PouringTime','HeatNo','float',NULL,NULL,NULL,1,0),
  ('dbo','PouringTime','Material','nvarchar',510,NULL,NULL,1,0),
  ('dbo','PouringTime','MaterialAutoNumber','nvarchar',510,NULL,NULL,1,0),
  ('dbo','PouringTime','NoLost','nvarchar',510,NULL,NULL,1,0),
  ('dbo','PouringTime','PouringNotes','nvarchar',510,NULL,NULL,1,0),
  ('dbo','PouringTime','PouringTime','float',NULL,NULL,NULL,1,0),
  ('dbo','PouringTime','TapTemperature','float',NULL,NULL,NULL,1,0),
  ('dbo','PouringTime','PourTemperature','float',NULL,NULL,NULL,1,0),
  ('dbo','PouringTime','ShakeoutDueDate','nvarchar',510,NULL,NULL,1,0),
  ('dbo','PouringTime','ActualShakeoutDate','nvarchar',510,NULL,NULL,1,0),
  ('dbo','PouringTime','ShakeoutComplete','bit',NULL,NULL,NULL,0,0),
  ('dbo','PouringTime','PourOrder','float',NULL,NULL,NULL,1,0),
  ('dbo','PouringTime','PouredBy','nvarchar',510,NULL,NULL,1,0),
  ('dbo','PouringTime','Furnace','float',NULL,NULL,NULL,1,0),
  ('dbo','PouringTime','Ladle','float',NULL,NULL,NULL,1,0),
  ('dbo','PouringTime','ID','float',NULL,NULL,NULL,1,0),
  ('dbo','ProcessData','Code','int',NULL,NULL,NULL,1,0),
  ('dbo','ProcessData','Name','nvarchar',100,NULL,NULL,1,0),
  ('dbo','ProcessData','Select','bit',NULL,NULL,NULL,1,0),
  ('dbo','QualityIssues','Id','int',NULL,NULL,NULL,0,1),
  ('dbo','QualityIssues','WorkOrderId','int',NULL,NULL,NULL,0,0),
  ('dbo','QualityIssues','InspectionRecordId','int',NULL,NULL,NULL,1,0),
  ('dbo','QualityIssues','Stage','nvarchar',200,NULL,NULL,0,0),
  ('dbo','QualityIssues','IssueType','nvarchar',510,NULL,NULL,1,0),
  ('dbo','QualityIssues','Severity','nvarchar',100,NULL,NULL,1,0),
  ('dbo','QualityIssues','Description','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','QualityIssues','DetectedBy','nvarchar',200,NULL,NULL,1,0),
  ('dbo','QualityIssues','Resolved','bit',NULL,NULL,NULL,1,0),
  ('dbo','QualityIssues','ResolutionNotes','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','QualityIssues','CreatedAt','datetime',NULL,NULL,NULL,1,0),
  ('dbo','ScrapRecords','Id','int',NULL,NULL,NULL,0,1),
  ('dbo','ScrapRecords','WorkOrderId','int',NULL,NULL,NULL,0,0),
  ('dbo','ScrapRecords','ScrapDate','date',NULL,NULL,NULL,1,0),
  ('dbo','ScrapRecords','ScrapReason','nvarchar',400,NULL,NULL,1,0),
  ('dbo','ScrapRecords','ScrapQty','int',NULL,NULL,NULL,1,0),
  ('dbo','ScrapRecords','ScrapWarehouse','nvarchar',200,NULL,NULL,1,0),
  ('dbo','ScrapRecords','ScrapOperator','nvarchar',200,NULL,NULL,1,0),
  ('dbo','ScrapRecords','CreatedAt','datetime',NULL,NULL,NULL,1,0),
  ('dbo','ScrapRecords','UpdatedAt','datetime',NULL,NULL,NULL,1,0),
  ('dbo','SerialNumbers','Id','int',NULL,NULL,NULL,0,1),
  ('dbo','SerialNumbers','WorkOrderId','int',NULL,NULL,NULL,0,0),
  ('dbo','SerialNumbers','Serial','nvarchar',200,NULL,NULL,0,0),
  ('dbo','SerialNumbers','Status','nvarchar',200,NULL,NULL,1,0),
  ('dbo','SerialNumbers','Created_At','datetime',NULL,NULL,NULL,1,0),
  ('dbo','users','id','int',NULL,NULL,NULL,0,1),
  ('dbo','users','username','nvarchar',510,NULL,NULL,0,0),
  ('dbo','users','hashed_password','nvarchar',510,NULL,NULL,0,0),
  ('dbo','users','role','nvarchar',100,NULL,NULL,0,0),
  ('dbo','users','created_at','datetime',NULL,NULL,NULL,0,0),
  ('dbo','WorkOrderDocuments','DocumentID','int',NULL,NULL,NULL,0,1),
  ('dbo','WorkOrderDocuments','WorkOrderRecordNo','bigint',NULL,NULL,NULL,1,0),
  ('dbo','WorkOrderDocuments','DocumentName','varchar',255,NULL,NULL,1,0),
  ('dbo','WorkOrderDocuments','DocumentType','varchar',50,NULL,NULL,1,0),
  ('dbo','WorkOrderDocuments','FilePath','varchar',255,NULL,NULL,1,0),
  ('dbo','WorkOrderDocuments','UploadedAt','datetime',NULL,NULL,NULL,1,0),
  ('dbo','WorkOrderDocuments','created_at','datetime',NULL,NULL,NULL,0,0),
  ('dbo','WorkOrderDocuments','updated_at','datetime',NULL,NULL,NULL,1,0),
  ('dbo','WorkOrderDocuments_Audit','AuditID','int',NULL,NULL,NULL,0,1),
  ('dbo','WorkOrderDocuments_Audit','ActionType','nvarchar',20,NULL,NULL,1,0),
  ('dbo','WorkOrderDocuments_Audit','ChangedAt','datetime',NULL,NULL,NULL,1,0),
  ('dbo','WorkOrderDocuments_Audit','ChangedBy','nvarchar',200,NULL,NULL,1,0),
  ('dbo','WorkOrderDocuments_Audit','Original_DocumentID','int',NULL,NULL,NULL,1,0),
  ('dbo','WorkOrderDocuments_Audit','DataBefore','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','WorkOrderDocuments_Audit','DataAfter','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','WorkOrders','RecordNo','int',NULL,NULL,NULL,0,1),
  ('dbo','WorkOrders','WorkOrderNo','nvarchar',200,NULL,NULL,0,0),
  ('dbo','WorkOrders','PartNo','nvarchar',200,NULL,NULL,0,0),
  ('dbo','WorkOrders','CustomerName','nvarchar',400,NULL,NULL,1,0),
  ('dbo','WorkOrders','AlloyCode','nvarchar',200,NULL,NULL,1,0),
  ('dbo','WorkOrders','QtyRequired','int',NULL,NULL,NULL,0,0),
  ('dbo','WorkOrders','RushDueDate','date',NULL,NULL,NULL,1,0),
  ('dbo','WorkOrders','SerialNo','nvarchar',200,NULL,NULL,1,0),
  ('dbo','WorkOrders','StatusNotes','nvarchar',510,NULL,NULL,1,0),
  ('dbo','WorkOrders','MoldingFinished','bit',NULL,NULL,NULL,1,0),
  ('dbo','WorkOrders','PouringFinished','bit',NULL,NULL,NULL,1,0),
  ('dbo','WorkOrders','HeatTreatFinished','bit',NULL,NULL,NULL,1,0),
  ('dbo','WorkOrders','MachiningFinished','bit',NULL,NULL,NULL,1,0),
  ('dbo','WorkOrders','AssemblyFinished','bit',NULL,NULL,NULL,1,0),
  ('dbo','WorkOrders','FinalInspComp','bit',NULL,NULL,NULL,1,0),
  ('dbo','WorkOrders','Status','nvarchar',100,NULL,NULL,1,0),
  ('dbo','WorkOrders_Audit','audit_id','int',NULL,NULL,NULL,0,1),
  ('dbo','WorkOrders_Audit','RecordNo','bigint',NULL,NULL,NULL,1,0),
  ('dbo','WorkOrders_Audit','action_type','nvarchar',40,NULL,NULL,1,0),
  ('dbo','WorkOrders_Audit','action_time','datetime',NULL,NULL,NULL,1,0),
  ('dbo','WorkOrders_Audit','action_user','nvarchar',200,NULL,NULL,1,0),
  ('dbo','WorkOrderSerialNumbers','SerialID','int',NULL,NULL,NULL,0,1),
  ('dbo','WorkOrderSerialNumbers','WorkOrderRecordNo','bigint',NULL,NULL,NULL,1,0),
  ('dbo','WorkOrderSerialNumbers','SerialNumber','varchar',50,NULL,NULL,1,0),
  ('dbo','WorkOrderSerialNumbers','DateAssigned','datetime',NULL,NULL,NULL,1,0),
  ('dbo','WorkOrderSerialNumbers','created_at','datetime',NULL,NULL,NULL,0,0),
  ('dbo','WorkOrderSerialNumbers','updated_at','datetime',NULL,NULL,NULL,1,0),
  ('dbo','WorkOrderSerialNumbers_Audit','AuditID','int',NULL,NULL,NULL,0,1),
  ('dbo','WorkOrderSerialNumbers_Audit','ActionType','nvarchar',20,NULL,NULL,1,0);
INSERT INTO #ExpectedColumns VALUES
  ('dbo','WorkOrderSerialNumbers_Audit','ChangedAt','datetime',NULL,NULL,NULL,1,0),
  ('dbo','WorkOrderSerialNumbers_Audit','ChangedBy','nvarchar',200,NULL,NULL,1,0),
  ('dbo','WorkOrderSerialNumbers_Audit','Original_SerialID','int',NULL,NULL,NULL,1,0),
  ('dbo','WorkOrderSerialNumbers_Audit','DataBefore','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','WorkOrderSerialNumbers_Audit','DataAfter','nvarchar',-1,NULL,NULL,1,0),
  ('dbo','WorkOrderStageLog','Id','int',NULL,NULL,NULL,0,1),
  ('dbo','WorkOrderStageLog','WorkOrderId','int',NULL,NULL,NULL,0,0),
  ('dbo','WorkOrderStageLog','StageName','nvarchar',200,NULL,NULL,0,0),
  ('dbo','WorkOrderStageLog','Action','nvarchar',100,NULL,NULL,0,0),
  ('dbo','WorkOrderStageLog','PerformedBy','nvarchar',200,NULL,NULL,1,0),
  ('dbo','WorkOrderStageLog','Notes','nvarchar',2000,NULL,NULL,1,0),
  ('dbo','WorkOrderStageLog','Timestamp','datetime',NULL,NULL,NULL,1,0);

;WITH Actual AS (
  SELECT
    s.name AS schema_name,
    t.name AS table_name,
    c.name AS column_name,
    ty.name AS data_type,
    c.max_length,
    c.precision AS precision_val,
    c.scale AS scale_val,
    c.is_nullable,
    c.is_identity
  FROM sys.tables t
  JOIN sys.schemas s ON s.schema_id = t.schema_id
  JOIN sys.columns c ON c.object_id = t.object_id
  JOIN sys.types ty ON ty.user_type_id = c.user_type_id
)
SELECT 'MISSING_TABLE' AS issue, e.schema_name, e.table_name, NULL AS column_name, NULL AS expected, NULL AS actual
FROM (SELECT DISTINCT schema_name, table_name FROM #ExpectedColumns) e
LEFT JOIN sys.tables t ON t.name = e.table_name
LEFT JOIN sys.schemas s ON s.schema_id = t.schema_id AND s.name = e.schema_name
WHERE t.object_id IS NULL OR s.schema_id IS NULL
UNION ALL
SELECT 'MISSING_COLUMN' AS issue, e.schema_name, e.table_name, e.column_name,
       CONCAT(e.data_type,'(',COALESCE(CONVERT(varchar(10),e.max_length),'null'),')') AS expected,
       NULL AS actual
FROM #ExpectedColumns e
LEFT JOIN Actual a
  ON a.schema_name=e.schema_name AND a.table_name=e.table_name AND a.column_name=e.column_name
WHERE a.column_name IS NULL
UNION ALL
SELECT 'MISMATCH' AS issue, e.schema_name, e.table_name, e.column_name,
       CONCAT(
         e.data_type,
         COALESCE(' len='+CONVERT(varchar(10),e.max_length),''),
         COALESCE(' p='+CONVERT(varchar(10),e.precision_val),''),
         COALESCE(' s='+CONVERT(varchar(10),e.scale_val),''),
         ' nullable='+CONVERT(varchar(1),e.is_nullable),
         ' identity='+CONVERT(varchar(1),e.is_identity)
       ) AS expected,
       CONCAT(
         a.data_type,
         COALESCE(' len='+CONVERT(varchar(10),a.max_length),''),
         COALESCE(' p='+CONVERT(varchar(10),a.precision_val),''),
         COALESCE(' s='+CONVERT(varchar(10),a.scale_val),''),
         ' nullable='+CONVERT(varchar(1),a.is_nullable),
         ' identity='+CONVERT(varchar(1),a.is_identity)
       ) AS actual
FROM #ExpectedColumns e
JOIN Actual a
  ON a.schema_name=e.schema_name AND a.table_name=e.table_name AND a.column_name=e.column_name
WHERE
  LOWER(a.data_type) <> LOWER(e.data_type)
  OR ISNULL(a.max_length,-999) <> ISNULL(e.max_length,-999)
  OR ISNULL(a.precision_val,-1) <> ISNULL(e.precision_val,-1)
  OR ISNULL(a.scale_val,-1) <> ISNULL(e.scale_val,-1)
  OR ISNULL(a.is_nullable,0) <> ISNULL(e.is_nullable,0)
  OR ISNULL(a.is_identity,0) <> ISNULL(e.is_identity,0)
ORDER BY issue, schema_name, table_name, column_name;

PRINT '=== Expected legacy columns: ' + CONVERT(varchar(20), (SELECT COUNT(*) FROM #ExpectedColumns)) + ' ===';
PRINT '=== Expected legacy tables: ' + CONVERT(varchar(20), (SELECT COUNT(DISTINCT schema_name+''.''+table_name) FROM #ExpectedColumns)) + ' ===';
