name: Frontend CI

on:
  push:
    paths:
      - "townley-platform/frontend/**"
      - ".github/workflows/frontend-ci.yml"
  pull_request:
    paths:
      - "townley-platform/frontend/**"
      - ".github/workflows/frontend-ci.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: |
            package-lock.json
            townley-platform/frontend/package-lock.json

      - name: Install dependencies
        working-directory: townley-platform/frontend
        run: npm ci

      - name: Run build
        working-directory: townley-platform/frontend
        run: npm run build
